name: Auto Push Images

on:
  push:
    paths:
      - 'path/to/images/**'

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure Git
        run: |
          git config --global user.email "sgod.dev001@gmail.com"
          git config --global user.name "SgodDev001"
      
      - name: Commit and Push Images
        run: |
          git add path/to/storage/*
          git commit -m "Auto-push new images"
          git push
